routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Auth::routes();

//Route::get("/user/register", [\App\Http\Controllers\UsersController::class, 'register'])->name('user.register');
//Route::get("/user/login", [\App\Http\Controllers\UsersController::class, 'login']);

Route::resource('user', \App\Http\Controllers\UsersController::class);
Route::resource('user.urls', \App\Http\Controllers\UrlsController::class);
Route::post('/unique', [\App\Http\Controllers\UrlsController::class, 'uniqueSlugCheck'])->name('slugCheck');
Route::post("/send_otp", [\App\Http\Controllers\UsersController::class, 'sendOtp'])->name('send-otp');
Route::post("/verify_otp", [\App\Http\Controllers\UsersController::class, 'verifyOtp'])->name('verify-otp');

//Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');






Route::get("/{slug}",[\App\Http\Controllers\UrlsController::class, 'redirectToUrl']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /*
     * Relationship Methods
     * */
    public function urls(): HasMany
    {
        return $this->hasMany(Url::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Carbon\Carbon;
use Carbon\Factory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\View\View;
use Twilio\Rest\Client;

class UsersController extends Controller
{

    public function index(): View
    {
//        Auth::logout();
//        $user = User::where("id",1)->first();
        $user = Auth::user();
        $urls = $user->urls;

        /*Most View URLs*/
        $mostViewedUrls = $urls->sortByDesc('hits')->take(10);

        /*Views By Month*/
        $viewsByMonth = [];
        $year = Carbon::now()->year;

        for ($i=0;$i<12;$i++){
            $num = 0;
            $monthlyUrls = $urls->whereBetween("created_at", [date($year.'-'.($i+1)), date($year.'-'.($i+2))])->all();
            foreach ($monthlyUrls as $url){
                $num += $url->hits;
            }
            $viewsByMonth[$i+1] = $num;
        }
//        dd($viewsByMonth);

        return view('users.index', compact([
            'urls',
            'mostViewedUrls',
            'viewsByMonth',
        ]));
    }

    public function store(Request $request)
    {
//        dd($request);
        /**
         * Validation
         */
        User::create([
            "name" => $request->name,
            "email" => $request->email,
            "number" => $request->phone,
            "username" => $request->username,
            "password" => Hash::make($request->password),
        ]);

        return redirect(route('user.index'));
    }

    public function edit(): View
    {
//        dd(auth()->user());
        $user = Auth::user();
        return view('users.edit', compact(
            'user',
        ));
    }

    public function update(Request $request, User $user)
    {
//        dd($request->yo);
        $data = [];
        if($request->name){
            $data['name'] = $request->name;
        }
        if($request->username){
            $data['username'] = $request->username;
        }
        if($request->phone){
            $data['phone'] = $request->phone;
        }
        if($request->email){
            $data['email'] = $request->email;
        }

        if($data != null){
            $user->update($data);
        }

        return redirect(route('user.index'));
    }

    public function register(): View
    {
        return view('users.register');
    }

    public function login(): View
    {
        return view('users.login');
    }

    public function sendOtp(Request $request)
    {
//        dd("hello");
        $number = $request->phone;
        $timeInSeconds = 10*60;
        $api = "m0O7VUCQv1DpBGKSMJdjyXx28P369slerEzAHZFbkNthf4gwiofEU7MuQoigTF38aRWXp90dbKe5krvS";

        if(session()->exists("user")){
            if(time() - session()->get("user")['start'] > $timeInSeconds){
                session()->forget("user");
                $otp = substr(str_shuffle("0123456789"), 0, 6);
            }else{
                //$otp = session()->get("user")['otp'];
                $otp = substr(str_shuffle("0123456789"), 0, 6);
            }
        }else{
            $otp = substr(str_shuffle("0123456789"), 0, 6);
        }
//        dd(session()->get($number));

        $sender_id = "TXTIND";
        $message = "Hello User\n Your OTP: $otp";

        $fields = array(
            "sender_id" => $sender_id,
            "message" => $message,
            "route" => "v3",
            "numbers" => $number,
        );

        $curl = curl_init();

        curl_setopt_array($curl, array(
            CURLOPT_URL => "https://www.fast2sms.com/dev/bulkV2",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_SSL_VERIFYHOST => 0,
            CURLOPT_SSL_VERIFYPEER => 0,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => json_encode($fields),
            CURLOPT_HTTPHEADER => array(
                "authorization: $api",
                "accept: */*",
                "cache-control: no-cache",
                "content-type: application/json"
            ),
        ));

        $response = curl_exec($curl);
        $err = curl_error($curl);

        curl_close($curl);

//        $err = false;
        if ($err) {
            dd($err);
            return [false];
        } else {
            session()->put("00000009769069674", [
                "hello" => "hi",
                "yo" => "hi",
            ]);
            session()->put("user", [
                'start' => time(),
                'otp' => Hash::make($otp)
            ]);
//            dd(session()->get($number));
            return [true];
        }
    }

    public function verifyOtp(Request $request)
    {
        $number = $request->phone;
//        echo $number;
//        dd($number, session()->get($number), session()->get('test'), session()->all());
        $otp = $request->otp;
        $timeInSeconds = 10 * 60;
//        dd(session()->all());

        if(session()->exists("user")) {
            if (time() - session()->get('user')['start'] > $timeInSeconds) {
                session()->forget('user');
                return [false];
            }
        }

        return [session()->exists('user') && Hash::check($otp, session()->get('user')['otp'])];
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('page-title')
Edit Profile
@endsection

@section('content')
<div class="registration-card mt-5">
    <div class="card">
        <form method="POST" action="{{ route('user.update', \Illuminate\Support\Facades\Auth::user()) }}" id="registration-form">
            @csrf
            @method('PUT')
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <span>Registration Form</span>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name" class="form-label mt-4">Name <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" value="{{$user->name}}">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="username" class="form-label mt-4">Username <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="username" name="username" placeholder="Enter username" value="{{$user->username}}">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="d-flex justify-content-between">
                                <label for="phone" class="form-label mt-4">
                                    Phone Number <span class="text-danger">*</span>
                                    <small class="text-muted">(We'll never share your phone number with anyone else.)</small>
                                </label>
                                <span class="align-self-end mb-2 text-success" id="verify-phone-btn" data-bs-toggle="modal" data-bs-target="#phoneVerificationModal" onclick="setPhoneInModal(this)">Edit</span>
                            </div>
                            <input type="text" class="form-control" id="phone" name="phone" aria-describedby="phone-notice" placeholder="Enter phone number" value="{{$user->phone}}" data-phone-verified="false" readonly>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="d-flex justify-content-between">
                                <label for="email" class="form-label mt-4">
                                    Email <span class="text-danger">*</span>
                                    <small class="text-muted">(We'll never share your email with anyone else.)</small>
                                </label>
                                <span class="align-self-end mb-2 text-success" id="verify-email-btn" data-bs-toggle="modal" data-bs-target="#emailVerificationModal" onclick="setEmailInModal(this)">Edit</span>
                            </div>
                            <input type="email" class="form-control" id="email" name="email" aria-describedby="phone-notice" placeholder="Enter email" value="{{$user->email}}" readonly>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-end">
                    <button class="btn btn-primary" id="register-btn" type="submit">Update</button>
                </div>
            </div>
        </form>
    </div>
</div>


{{--Phone Registration Modal--}}
<div class="modal fade" id="phoneVerificationModal" tabindex="-1" aria-labelledby="phoneVerificationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="phoneVerificationModalLabel">Verify your Phone Number</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="phone-input">
                    <label for="unverified_phone_number" class="form-label mt-4">
                        Phone Number <span class="text-danger">*</span>
                        <small class="text-muted">(Please verify phone number is correct.)</small>
                    </label>
                    <input type="text" class="form-control" id="unverified_phone_number" name="unverified_phone_number" placeholder="9999999999">
                </div>
                <div class="otp-input-card">
                    <label for="otp-input" class="form-label mt-4">
                        OTP <span class="text-danger">*</span>
                        <small class="text-muted">(Received on your phone number.)</small>
                    </label>
                    <input type="text" class="form-control" id="otp-input" name="otp-input">
                    <span id="otp-error" class="text-danger"></span>
                </div>
                <div id="recaptcha-container" class="mt-4"></div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" id="get-otp-btn" onclick="sendOtp()">Get OTP</button>
                <button class="btn btn-success" id="verify-otp-btn" onclick="verifyOtp()" disabled="disabled">Verify OTP</button>
            </div>
        </div>
    </div>
</div>
{{--Phone Registration Modal--}}
@endsection

@section('page-level-scripts')
    <script>
        function setPhoneInModal(element) {
            console.log("ji");
            /* Updating the phone number in the modal */
            var phoneNumber = $("#phone").val();
            $("#unverified_phone_number").val(phoneNumber);
        }

        function sendOtp(){
            $.ajax({
                url: "{{route('send-otp')}}",
                method: "POST",
                data: {
                    "_token": "{{csrf_token()}}",
                    "phone": $("#unverified_phone_number").val(),
                },
                success: function (data){
                    if(data[0]){
                        $('#verify-otp-btn').removeAttr('disabled');
                        console.log("OTP Sent");
                    }else{
                        console.log('Failed');
                    }
                }
            });
        }

        function verifyOtp(){
            $.ajax({
                url: "{{route('verify-otp')}}",
                method: "POST",
                data: {
                    "_token": "{{csrf_token()}}",
                    "phone": $("#unverified_phone_number").val(),
                    "otp": $("#otp-input").val(),
                },
                success: function (data){
                    if(data[0]){
                        /**
                         * User Signed in successfully (Now steps to be performed)
                         * 1. Fill the phone number into the field
                         * 2. Disable the field from editing
                         * 3. Remove the verify Button
                         * 4. Change the UI of the Input Field
                         * 5. Enable the Register button
                         * 6. Add a data attribute 'data-validated' for further use
                         * 7. Close the modal
                         */
                        /*Step 1*/

                        var phoneNumber = $('#unverified_phone_number').val();
                        $('#phone').val(phoneNumber);

                        /*Step 2*/
                        $('#phone').attr('readonly', 'readonly');

                        /*Step 3*/
                        $('#verify-phone-btn').remove();

                        /*Step 4*/
                        $('#phone').addClass('is-valid');
                        $('#phone').attr('data-phone-verified', 'false');

                        /*Step 5*/
                        $('#register-btn').removeAttr('disabled');

                        /*Step 6*/
                        $('#phone').attr('data-validated', 'true');

                        /*Step 7*/
                        $(function () {
                            $('#phoneVerificationModal').modal('toggle');
                        });
                    }else{
                        console.log('Failed');
                    }
                }
            });
        }
    </script>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('page-title')
Index
@endsection

@section('content')
    <div class="mt-5">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">Most Visited URLs</div>
                    <div class="card-body">
                        <canvas id="most_visited_urls_chart"></canvas>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">Total URL Views By Month</div>
                    <div class="card-body">
                        <canvas id="views_by_month_chart"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-5">
        <div class="card">
            <div class="card-header">URL Collection</div>
            <div class="card-body">
                <table id="table_id" class="display">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Actual URL</th>
                            <th>Short URL</th>
                            <th>Click Count</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($urls as $url)
                            <tr>
                                <td>{{$url->title}}</td>
                                <td><a href="{{$url->actual_url}}">{{$url->actual_url}}</a></td>
                                <td><a href="www.shorturl.com/{{$url->slug}}">www.shorturl.com/{{$url->slug}}</a></td>
                                <td>{{$url->clickCount()}}</td>
                                <td>
                                    <div class="btn btn-info btn-edit" id="btn_edit" data-id="{{$url->id}}" data-toggle="modal" data-target="#editUrlModal" onclick="fillEditUrlDetails(this)">
                                        <span class="fa fa-pen"></span>
                                    </div>
                                    <div class="btn btn-danger btn-delete " data-id="{{$url->id}}" data-toggle="modal" data-target="#deleteUrlModal" onclick="fillDeleteUrlDetails(this)">
                                        <span class="fa fa-trash"></span>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {{--Create URL Modal--}}
    <div class="modal fade" id="createUrlModal" tabindex="-1" aria-labelledby="createUrlModalLabel" aria-hidden="true">
        <form action="{{route('user.urls.store', \Illuminate\Support\Facades\Auth::user())}}" method="POST" id="create_url_form">
            @csrf
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="createUrlModalLabel">Create A URL</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group mt-3">
                            <label for="title" class="form-label">Title for URL <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="title" name="title" placeholder="Enter title">
                            @error('title')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group mt-3">
                            <label for="actual-url" class="form-label">Actual URL <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="actual-url" name="actual_url" placeholder="https:://www.yourwebsite.com">
                            @error('actual_url')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-check mt-3">
                            <input class="form-check-input" type="checkbox" value="checked" name="custom_url_check" id="custom-url-check" onchange="customUrlField(this)">
                            <label class="form-check-label" for="flexCheckChecked">
                                Do you want to create a custom URL?
                            </label>
                        </div>
                        <div class="form-group" id="custom-url-card">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-primary" id="create_url_btn" name="create_url_btn">Create URL</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    {{--Create URL Modal--}}

    {{--Edit URL Modal--}}
    <div class="modal fade" id="editUrlModal" tabindex="-1" aria-labelledby="editUrlModalLabel" aria-hidden="true">
        <form action="" method="POST" id="edit_url_form">
            @csrf
            @method('PUT')
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="editUrlModalLabel">Edit A URL</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group mt-3">
                            <label for="edit_url_title" class="form-label">Title for URL <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="edit_url_title" name="edit_url_title" placeholder="Enter title">
                            <input type="hidden" name="edit_url_id" id="edit_url_id">
                        </div>
{{--                        <div class="form-group mt-3">--}}
{{--                            <label for="edit_actual_url" class="form-label">Actual URL <span class="text-danger">*</span></label>--}}
{{--                            <input type="text" class="form-control" id="edit_actual_url" name="edit_actual_url" placeholder="Enter actual url">--}}
{{--                        </div>--}}
                        <div class="form-group mt-3">
                            <label for="edit_custom_url" class="form-label">Custom URL <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="edit_custom_url" name="edit_custom_url" placeholder="Enter custom url">
                            <span class="text-danger" id="edit_url_error"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-primary" id="edit_url_btn" name="edit_url_btn">Edit URL</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    {{--Edit URL Modal--}}

    {{--Delete URL Modal--}}
    <div class="modal fade" id="deleteUrlModal" tabindex="-1" aria-labelledby="deleteUrlModalLabel" aria-hidden="true">
        <form action="" method="POST" id="delete_url_form">
            @csrf
            @method('DELETE')
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteUrlModalLabel">Delete A URL</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete this Url?</p>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-danger" id="delete_url_btn" name="delete_url_btn">Delete URL</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    {{--Delete URL Modal--}}
@endsection

@section('page-level-styles')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
@endsection

@section('page-level-scripts')
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
<script>
    /*
    * Fill the edit modal with url details
    * */
    function fillEditUrlDetails(element)
    {
        var id = $(element).data('id');

        var url = "{{route('user.urls.edit', ['@', '@'])}}".replace('@', "{{\Illuminate\Support\Facades\Auth::user()->id}}").replace('@', id);
        $.ajax({
            url: url,
            method: 'GET',
            success: function (data){
                data = JSON.parse(data);
                console.log(data);
                $('#edit_url_id').val(data.id);
                $('#edit_url_title').val(data.title);
                $('#edit_actual_url').val(data.actual_url);
                $('#edit_custom_url').val(data.slug);

                $('#editUrlModal').modal('show');

                var urlLink = "{{route('user.urls.update', ['@', '@'])}}".replace('@', "{{\Illuminate\Support\Facades\Auth::user()->id}}").replace('@', id);
                $("#edit_url_form").attr('action', urlLink);
            },
            error: function (data){
                alert(data);
            }
        });
    }

    /*
    * Fill the delete modal with url details
    * */
    function fillDeleteUrlDetails(element)
    {
        var id = $(element).data('id');
        var urlLink = "{{route('user.urls.destroy', ['@', '@'])}}".replace('@', "{{\Illuminate\Support\Facades\Auth::user()->id}}").replace('@', id);
        $("#delete_url_form").attr('action', urlLink);
        $('#deleteUrlModal').modal('show');
    }

    $(function (){

        /**
         * To initialize datatable
         * */
        $('#table_id').DataTable();

        /**
         * To validate the create Url form details
         * */
        $('#create_url_form').validate({
           rules: {
               "title": {
                   required: true,
               },
               "actual_url": {
                   required: true,
                   url: true,
               },
               "custom_url_input": {
                   required: true,
               },
           },
           submitHandler: function (form) {

               var slug = $('#custom-url-input').val();
               var url = "{{route('slugCheck')}}";
               console.log(url);
               $.ajax({
                   url: url,
                   method: "POST",
                   data: {
                       _token: "{{ csrf_token() }}",
                       slug: slug
                   },
                   success: function (data){
                       console.log(data);
                       // return;
                       if(data[0]){
                           form.submit();
                           // $('#create_url_form').submit();
                           {{--window.location.href = "{{route('user.index')}}";--}}
                       }else{
                           $('#create_url_error').text('Url is already been taken!')
                       }
                   },
                   error: function (data){
                       alert(data);
                   }
               });

           }
       });

        /**
         * To validate the edit Url form details
         * */
        $('#edit_url_form').validate({
            rules: {
                "edit_url_title": {
                    required: true,
                },
                "edit_custom_url": {
                    required: true,
                },
            },
            submitHandler: function (form) {

                var slug = $('#edit_custom_url').val();
                var id = $('#edit_url_id').val();
                console.log(id);
                var url = "{{route('slugCheck')}}";
                console.log(url);
                $.ajax({
                    url: url,
                    method: "POST",
                    data: {
                        _token: "{{ csrf_token() }}",
                        slug: slug,
                        id: id,
                    },
                    success: function (data){
                        // console.log(data[0]);
                        // return;
                        if(data[0]){
                            form.submit();
                            // $('#edit_url_form').submit();
                            {{--window.location.href = "{{route('user.index')}}";--}}
                        }else{
                            $('#edit_url_error').text('Url is already been taken!')
                        }
                    }
                });

                // form.submit();
            }
        });
    });

    /**
     * To remove the error of previously taken slug for next time
     * */
    $('#edit_custom_url').on('change', function (){
       $('#edit_url_error').text('');
    });

</script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{{asset('js/users/index.js')}}"></script>
<script>
    initMostViewedUrlGraph('{!! json_encode($mostViewedUrls->toArray()) !!}');
    initViewsByMonthGraph('{!! json_encode($viewsByMonth) !!}');
</script>
@endsection