routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Auth::routes();

//Route::get("/user/register", [\App\Http\Controllers\UsersController::class, 'register'])->name('user.register');
//Route::get("/user/login", [\App\Http\Controllers\UsersController::class, 'login']);

Route::resource('user', \App\Http\Controllers\UsersController::class);
Route::resource('user.urls', \App\Http\Controllers\UrlsController::class);
Route::post('/unique', [\App\Http\Controllers\UrlsController::class, 'uniqueSlugCheck'])->name('slugCheck');
Route::post("/send_otp", [\App\Http\Controllers\UsersController::class, 'sendOtp'])->name('send-otp');
Route::post("/verify_otp", [\App\Http\Controllers\UsersController::class, 'verifyOtp'])->name('verify-otp');

//Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');






Route::get("/{slug}",[\App\Http\Controllers\UrlsController::class, 'redirectToUrl']);

resources/views/layouts/_footer.blade.php
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-primary text-white mt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <ul class="list-unstyled mt-5">
                    <li class="mb-2"><strong>Why Bitly?</strong></li>
                    <li>Bitly 101</li>
                    <li>Integrations & API</li>
                    <li>Enterprise Class</li>
                    <li>Pricing</li>
                </ul>
                <ul class="list-unstyled mt-5">
                    <li class="mb-2"><strong>Company</strong></li>
                    <li>About Bitly</li>
                    <li>Careers</li>
                    <li>Partner</li>
                    <li>Press</li>
                    <li>Contact</li>
                    <li>Reviews</li>
                </ul>
            </div>
            <div class="col-md-3">
                <ul class="list-unstyled mt-5">
                    <li class="mb-2"><strong>Why Bitly?</strong></li>
                    <li>Bitly 101</li>
                    <li>Integrations & API</li>
                    <li>Enterprise Class</li>
                    <li>Pricing</li>
                </ul>
                <ul class="list-unstyled mt-5">
                    <li class="mb-2"><strong>Company</strong></li>
                    <li>About ShorturL</li>
                    <li>Career</li>
                    <li>Partner</li>
                    <li>Contact</li>
                    <li>Reviews</li>
                </ul>
            </div>
            <div class="col-md-3">
                <ul class="list-unstyled mt-5">
                    <li class="mb-2"><strong>Why Bitly?</strong></li>
                    <li>Bitly 101</li>
                    <li>Integrations & API</li>
                    <li>Enterprise Class</li>
                    <li>Pricing</li>
                </ul>
                <ul class="list-unstyled mt-5">
                    <li class="mb-2"><strong>Company</strong></li>
                    <li>About ShorturL</li>
                    <li>Career</li>
                    <li>Partner</li>
                    <li>Contact</li>
                    <li>Reviews</li>
                </ul>
            </div>
            <div class="col-md-3">
                <div class="mt-5">
                    <h3>ShorturL</h3>
                    <small>© 2022 ShorturL |
                        Handmade in San Francisco, Denver, New York City, Bielefeld, and all over the world.</small>
                </div>
                <div class="mt-3">
                    <a href="" class="mr-3"><span class="fab fa-2x fa-facebook"></span></a>
                    <a href="" class="mr-3"><span class="fab fa-2x fa-instagram"></span></a>
                    <a href="" class="mr-3"><span class="fab fa-2x fa-twitter"></span></a>
                    <a href="" class="mr-3"><span class="fab fa-2x fa-pinterest"></span></a>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/_header.blade.php
{{--{{session()->flush()}}--}}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{route('home')}}">ShorturL</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        @if(\Illuminate\Support\Facades\Auth::user() != null)
            <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{{route('user.index', \Illuminate\Support\Facades\Auth::user())}}">Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a type="button" class="nav-link" data-bs-toggle="modal" data-bs-target="#createUrlModal">Create a URL</a>
                </li>
            </ul>

            <div class="d-flex justify-content-end">
                <div class="mr-5">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{\Illuminate\Support\Facades\Auth::user()->name}}</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{{route('user.edit', \Illuminate\Support\Facades\Auth::user())}}">Edit Profile</a>
                                <div class="dropdown-divider"></div>
                                <form action="{{route('logout')}}" method="POST">
                                    @csrf
                                    <button class="dropdown-item" type="submit">Logout</button>
                                </form>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        @else
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Why ShorturL?</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item">ShorturL 101</a>
                            <a class="dropdown-item">Integrations & API</a>
                            <a class="dropdown-item">Enterprise Class</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Solutions</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item"><span class="fa fa-pen mr-1"></span>Social Media</a>
                            <a class="dropdown-item">Digital Marketing</a>
                            <a class="dropdown-item">Customer Service</a>
                            <a class="dropdown-item">For Developers</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a type="button" class="nav-link">Features</a>
                    </li>
                    <li class="nav-item">
                        <a type="button" class="nav-link">Pricing</a>
                    </li>
                    <li class="nav-item">
                        <a type="button" class="nav-link">Resources</a>
                    </li>
                </ul>

                <div class="d-flex justify-content-end">
                    <div class="mr-5">
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a type="button" href="{{route('login')}}" class="nav-link">Log in</a>
                            </li>
                            <li class="nav-item">
                                <a type="button" href="{{route('register')}}" class="nav-link">Sign up</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        @endif
    </div>
</nav>

resources/views/layouts/_message.blade.php
{{--Uncomment agter completion of code--}}

{{--
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <p>This is a Success Message</p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        <div class="col-md-12">
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <p>This is an Error Message</p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    </div>
    <div class="row" id="status"></div>
</div>
--}}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@yield('page-title')</title>

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.0/css/all.min.css" integrity="sha512-gRH0EcIcYBFkQTnbpO8k0WlsD20x5VzjhOA1Og8+ZUAhcMUCvd+APD35FJw3GzHAP3e+mP28YcDJxVr745loHw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/sandstone/bootstrap.min.css" integrity="sha384-zEpdAL7W11eTKeoBJK1g79kgl9qjP7g84KfK3AZsuonx38n8ad+f5ZgXtoSDxPOh" crossorigin="anonymous">
{{--    <link href="{{ asset('css/app.css') }}" rel="stylesheet">--}}

    <style>
        /* To show every error in red */
        .error{
            color: red;
        }
    </style>
    @yield('page-level-styles')


</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
        @include("layouts._header")
        <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container">
                @include("layouts._message")
                @yield('content')
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
    @include('layouts._footer')
    <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Bootstrap core JavaScript-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

<!-- JQuery CDN-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<!-- Jquery Validator-->
<script src="{{ asset('js/jquery-validator/validate.min.js') }}"></script>

@yield('page-level-scripts')
</body>

</html>